// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./src/components/BaseAlert.vue')['default']
    BaseBadge: typeof import('./src/components/BaseBadge.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseCaption: typeof import('./src/components/BaseCaption.vue')['default']
    BaseCard: typeof import('./src/components/BaseCard.vue')['default']
    BaseCarousel: typeof import('./src/components/BaseCarousel.vue')['default']
    BaseCheckbox: typeof import('./src/components/BaseCheckbox.vue')['default']
    BaseDialog: typeof import('./src/components/BaseDialog.vue')['default']
    BaseDivider: typeof import('./src/components/BaseDivider.vue')['default']
    BaseHeading: typeof import('./src/components/BaseHeading.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    BaseImage: typeof import('./src/components/BaseImage.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseLogo: typeof import('./src/components/BaseLogo.vue')['default']
    BasePageLoader: typeof import('./src/components/BasePageLoader.vue')['default']
    BasePagination: typeof import('./src/components/BasePagination.vue')['default']
    BaseParagraph: typeof import('./src/components/BaseParagraph.vue')['default']
    BasePopover: typeof import('./src/components/BasePopover.vue')['default']
    BasePoster: typeof import('./src/components/BasePoster.vue')['default']
    BaseScrollUp: typeof import('./src/components/BaseScrollUp.vue')['default']
    BaseSearch: typeof import('./src/components/BaseSearch.vue')['default']
    BaseSection: typeof import('./src/components/BaseSection.vue')['default']
    BaseSelect: typeof import('./src/components/BaseSelect.vue')['default']
    BaseTextarea: typeof import('./src/components/BaseTextarea.vue')['default']
    BaseWrapper: typeof import('./src/components/BaseWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
