export enum Action {
  CHANGE_PAGE = 'CHANGE_PAGE',
  FETCH_DATA = 'FETCH_DATA',
  FILTER_MOVIES = 'FILTER_MOVIES',
  FILTER_TV_SHOWS = 'FILTER_TV_SHOWS',
  HIDE_ALERT = 'HIDE_ALERT',
  ON_PAGINATION = 'ON_PAGINATION',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  SHOW_ALERT = 'SHOW_ALERT',
  SHOW_NEXT_ELEMENT = 'SHOW_NEXT_ELEMENT',
  SHOW_PREV_ELEMENT = 'SHOW_PREV_ELEMENT',
  USE_FETCH = 'USE_FETCH',
}
