export enum Getter {
  GET_ALERTS = 'GET_ALERTS',
  GET_CURRENT_PAGE = 'GET_CURRENT_PAGE',
  GET_MOVIES_LIST = 'GET_MOVIES_LIST',
  GET_TV_SHOWS_LIST = 'GET_TV_SHOWS_LIST',
  GET_ERROR = 'GET_ERROR',
  GET_FETCHING = 'GET_FETCHING',
}
