export enum Mutation {
  HIDE_ALERT = 'HIDE_ALERT',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  SHOW_ALERT = 'SHOW_ALERT',
  UPDATE_ERROR = 'UPDATE_ERROR',
  UPDATE_FETCHING = 'UPDATE_FETCHING',
  UPDATE_MOVIES_LIST = 'UPDATE_MOVIES_LIST',
  UPDATE_TV_SHOWS_LIST = 'UPDATE_TV_SHOWS_LIST',
}
